/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/parse-groceries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract structured ingredient data from unstructured text
         * @description An advanced AI-driven parser that transforms unstructured grocery lists or recipe ingredients into high-quality structured data. It automatically detects quantities, standardized units, and organizes items into logical supermarket categories like Produce, Dairy, or Pantry.
         */
        post: operations["parse-groceries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/substitute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get AI-powered ingredient alternatives based on dish context
         * @description Provides intelligent, context-aware ingredient alternatives based on the specific dish being prepared. Each suggestion includes adjusted quantities, a detailed explanation of why the substitute works, and an impact score reflecting how much it might change the final flavor or texture.
         */
        post: operations["substitute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask-assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expert culinary advice for recipes and techniques
         * @description A direct line to a specialized culinary AI expert. Use this endpoint to generate complex cooking instructions, ask for professional wine pairings, or get advice on how to fix a recipe. It understands culinary techniques and flavor profiles at a professional level.
         */
        post: operations["ask-assistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify API operational status and system uptime
         * @description Validates the API's operational status and connectivity to backend services. This endpoint is ideal for monitoring uptime and ensuring the MonAmiChef engine is ready to process requests.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculate-calories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate your recommended daily nutrition intake according to your goal
         * @description Inputting your height, gender, age and estimated daily physical activity find out your BMR
         */
        post: operations["calories-calculator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatSessionsController_getChat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatSessionsController_getAllUserChats"];
        put?: never;
        post: operations["ChatSessionsController_createChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatSessionsController_updateChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ParseGroceriesRequestDto: {
            text: string;
        };
        ParseGroceriesResponseDto_Output: {
            /** @description The name of the recipe */
            recipe_name: string;
            prep_infos: {
                prep_time_min: number;
                servings: number;
                difficulty: string;
            };
            macros_per_servings: {
                calories: number;
                proteins: number;
                carbs: number;
                fat: number;
                fibers: number;
            };
            dietary_info: {
                vegetarian: boolean;
                dairy_free: boolean;
                vegan: boolean;
                gluten_free: boolean;
            };
            /** @description A list of ingredient object */
            ingredients: {
                /** @description The name of the ingredient */
                name: string;
                /** @description The quantity of the ingredient */
                quantity: number;
                /** @description The unit of the quantity of an ingredient */
                unit: string;
                /** @description The category of an ingredient */
                category: string;
                /** @description The original full line of text */
                raw_text: string;
            }[];
            substitutions: {
                /** @description The ingredient to substitute */
                ingredient_name: string;
                /** @description The replacement of ingredient_name */
                replacement: string;
                /** @description The consequences of the replacement (eg: To make it vegan) */
                reason: string;
            }[];
        };
        SubstituteIngredientsRequestDto: {
            /** @description The user input text of ingredients to substitute + possible context */
            text: string;
        };
        SubstituteIngredientsResponseDto_Output: {
            /** @description Optional detected context, eg: Curry chicken */
            optional_detected_context?: string;
            /** @description Summary note of the substitutions response from the ai */
            summary_note: string;
            substitutions: {
                /** @description The ingredient to replace */
                to_replace: string;
                replacement: {
                    /** @description The replacement ingredient */
                    name: string;
                    /** @description The quantity of the replacement */
                    quantity?: number;
                    quantity_unit: string;
                    /** @description The reason of the replacement */
                    explanation: string;
                    /** @description The impact of the replacement */
                    impact: string;
                    /** @description The impact score on the dish taste of the replacemant */
                    impact_score: number;
                }[];
            }[];
        };
        AskAssistantRequestDto: {
            /** @description The user input text of ingredients to substitute + possible context */
            text: string;
        };
        CalculateCaloriesRequestDto: {
            age: number;
            /** @description User height */
            height: {
                value: number;
                /** @enum {string} */
                unit: "cm" | "inch";
            };
            /** @description User weight */
            weight: {
                value: number;
                /** @enum {string} */
                unit: "kgs" | "lbs";
            };
            /**
             * @description User gender
             * @enum {string}
             */
            gender: "male" | "female";
            /**
             * @description User daily physical activity
             * @enum {string}
             */
            physical_activity: "sedentary" | "light" | "moderate" | "active" | "very active" | "extra active";
        };
        CalculateCaloriesResponseDto_Output: {
            /** @description Basal Metabolic Rate (calories burned at rest) */
            bmr: number;
            /** @description Total Daily Energy Expenditure (calories burned with activity) */
            tdee: number;
            /** @constant */
            unit: "kcal/day";
            fluctuation: {
                [key: string]: {
                    daily_macros: {
                        calories: number;
                        proteins: number;
                        carbs: number;
                        fiber: number;
                        fat: number;
                    };
                    weight_impact: {
                        text: string;
                        variation: number;
                        /** @enum {string} */
                        unit: "kgs" | "lbs";
                    };
                };
            };
        };
        GetChatSessionResponseDto_Output: {
            /** Format: uuid */
            id: string;
            title: string;
            messages: {
                id: string;
                chatId: string;
                /** @enum {string} */
                role: "user" | "model";
                content: string;
                createdAt: string;
            }[];
            createdAt: string;
            updatedAt: string;
        };
        GetAllChatsSessionResponseDto_Output: {
            chats: {
                /** Format: uuid */
                id: string;
                title: string;
                createdAt: string;
                updatedAt: string;
            }[];
        };
        CreateChatSessionRequestDto: {
            firstMessage: string;
            /** @default [] */
            preferences: ("high_protein" | "high_fiber" | "low_carb" | "balanced" | "high_carb" | "low_fat" | "vegetarian" | "vegan" | "italian" | "mexican" | "mediterranean" | "american" | "french" | "indian" | "thai" | "chinese" | "japanese" | "middle_eastern" | "korean" | "african" | "breakfast" | "lunch" | "dinner" | "appetizer" | "dessert" | "snack" | "smoothie_drink" | "under_15" | "under_30" | "one_hour_max" | "slow_cook" | "chicken" | "beef" | "pork" | "fish" | "seafood" | "lamb" | "turkey" | "duck" | "tomatoes" | "onions" | "carrots" | "bell_peppers" | "broccoli" | "spinach" | "mushrooms" | "zucchini" | "potatoes" | "garlic" | "lettuce" | "cucumber")[];
            /** @default [] */
            exclude: ("high_protein" | "high_fiber" | "low_carb" | "balanced" | "high_carb" | "low_fat" | "vegetarian" | "vegan" | "italian" | "mexican" | "mediterranean" | "american" | "french" | "indian" | "thai" | "chinese" | "japanese" | "middle_eastern" | "korean" | "african" | "breakfast" | "lunch" | "dinner" | "appetizer" | "dessert" | "snack" | "smoothie_drink" | "under_15" | "under_30" | "one_hour_max" | "slow_cook" | "chicken" | "beef" | "pork" | "fish" | "seafood" | "lamb" | "turkey" | "duck" | "tomatoes" | "onions" | "carrots" | "bell_peppers" | "broccoli" | "spinach" | "mushrooms" | "zucchini" | "potatoes" | "garlic" | "lettuce" | "cucumber")[];
        };
        CreateChatSessionResponseDto_Output: {
            /** Format: uuid */
            id: string;
            title: string;
            messages: {
                id: string;
                chatId: string;
                /** @enum {string} */
                role: "user" | "model";
                content: string;
                createdAt: string;
            }[];
            createdAt: string;
            updatedAt: string;
        };
        UpdateChatSessionRequestDto: {
            message: string;
            /** @default [] */
            preferences: ("high_protein" | "high_fiber" | "low_carb" | "balanced" | "high_carb" | "low_fat" | "vegetarian" | "vegan" | "italian" | "mexican" | "mediterranean" | "american" | "french" | "indian" | "thai" | "chinese" | "japanese" | "middle_eastern" | "korean" | "african" | "breakfast" | "lunch" | "dinner" | "appetizer" | "dessert" | "snack" | "smoothie_drink" | "under_15" | "under_30" | "one_hour_max" | "slow_cook" | "chicken" | "beef" | "pork" | "fish" | "seafood" | "lamb" | "turkey" | "duck" | "tomatoes" | "onions" | "carrots" | "bell_peppers" | "broccoli" | "spinach" | "mushrooms" | "zucchini" | "potatoes" | "garlic" | "lettuce" | "cucumber")[];
            /** @default [] */
            exclude: ("high_protein" | "high_fiber" | "low_carb" | "balanced" | "high_carb" | "low_fat" | "vegetarian" | "vegan" | "italian" | "mexican" | "mediterranean" | "american" | "french" | "indian" | "thai" | "chinese" | "japanese" | "middle_eastern" | "korean" | "african" | "breakfast" | "lunch" | "dinner" | "appetizer" | "dessert" | "snack" | "smoothie_drink" | "under_15" | "under_30" | "one_hour_max" | "slow_cook" | "chicken" | "beef" | "pork" | "fish" | "seafood" | "lamb" | "turkey" | "duck" | "tomatoes" | "onions" | "carrots" | "bell_peppers" | "broccoli" | "spinach" | "mushrooms" | "zucchini" | "potatoes" | "garlic" | "lettuce" | "cucumber")[];
        };
        UpdateChatSessionResponseDto_Output: {
            /** Format: uuid */
            id: string;
            title: string;
            messages: {
                id: string;
                chatId: string;
                /** @enum {string} */
                role: "user" | "model";
                content: string;
                createdAt: string;
            }[];
            createdAt: string;
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "parse-groceries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseGroceriesRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseGroceriesResponseDto_Output"];
                };
            };
        };
    };
    substitute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubstituteIngredientsRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstituteIngredientsResponseDto_Output"];
                };
            };
        };
    };
    "ask-assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskAssistantRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "calories-calculator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateCaloriesRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateCaloriesResponseDto_Output"];
                };
            };
        };
    };
    ChatSessionsController_getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetChatSessionResponseDto_Output"];
                };
            };
        };
    };
    ChatSessionsController_getAllUserChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllChatsSessionResponseDto_Output"];
                };
            };
        };
    };
    ChatSessionsController_createChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatSessionRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateChatSessionResponseDto_Output"];
                };
            };
        };
    };
    ChatSessionsController_updateChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatSessionRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateChatSessionResponseDto_Output"];
                };
            };
        };
    };
}
